// <auto-generated />
using System;
using HotelCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelCrud.Migrations
{
    [DbContext(typeof(HotelCaliforniaDbContext))]
    partial class HotelCaliforniaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelCrud.Models.Habitacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Habitaci__3214EC07470534DA");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("HotelCrud.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Personas__3214EC070067F93E");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("HotelCrud.Models.PersonaRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PersonaR__3214EC0765C00352");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdRol");

                    b.ToTable("PersonaRol", (string)null);
                });

            modelBuilder.Entity("HotelCrud.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FechaEntrada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reservas__3214EC074A615DA4");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdPersona");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelCrud.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC0759E20D9B");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HotelCrud.Models.PersonaRol", b =>
                {
                    b.HasOne("HotelCrud.Models.Persona", "IdPersonaNavigation")
                        .WithMany("PersonaRols")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__PersonaRo__IdPer__4D94879B");

                    b.HasOne("HotelCrud.Models.Role", "IdRolNavigation")
                        .WithMany("PersonaRols")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__PersonaRo__IdRol__4E88ABD4");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("HotelCrud.Models.Reserva", b =>
                {
                    b.HasOne("HotelCrud.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdHabitacion")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdHabi__5441852A");

                    b.HasOne("HotelCrud.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__IdPers__534D60F1");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("HotelCrud.Models.Habitacione", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelCrud.Models.Persona", b =>
                {
                    b.Navigation("PersonaRols");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelCrud.Models.Role", b =>
                {
                    b.Navigation("PersonaRols");
                });
#pragma warning restore 612, 618
        }
    }
}
